### ISSUE TITLE
there is no sound when i click the speak button ..

### ISSUE THREAD

**Issue by ajphukan** [max-mapper/bopomofo#1]

**Comment by max-mapper** [comment]
does your browser support the https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis API, and do you get a JS error?

**Comment by ajphukan** [comment]
i have checked on both mozilla and chrome 
both are latest version and support the api  .. 
and i didn't get any js error ..

In chrome there is a animation when character change but in mozilla there is no animation.

**Comment by max-mapper** [comment]
i'm only supporting mobile safari on ios right now, sorry

**Comment by ajphukan** [comment]
okk thanks ...
